# Commands to start on workspace startup
image: gitpod/workspace-python-3.9
tasks:
  - init: pip install -r requirements.txt
    command: make livehtml
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
